name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd snackbox
            git pull
            docker-compose down && docker-compose up --build -d
      - uses: actions/checkout@v2
      - name: upload images to docker hub
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u DOCKER_USER -p DOCKER_PASSWORD
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/snackbox:latest
          
        
